#!/bin/bash
find . -name project.clj -exec sed -i "s/(def VERSION \".*\")/(def VERSION \"$1\")/g" '{}' \;
sed -i "s/\[yada \".*\"\]/\[yada \"$1\"\]/g" doc/install.adoc
sed -i "s/\[yada \".*\"\]/\[yada \"$1\"\]/g" README.md
sed -i "s/\[yada\/lean \".*\"\]/\[yada\/lean \"$1\"\]/g" README.md
