#!/bin/sh
ext="sedbak$$"
find . -name project.clj -exec sed -i.$ext "s/(def VERSION \".*\")/(def VERSION \"$1\")/g" '{}' \;
#sed -i.$ext "s/\[yada \".*\"\]/\[yada \"$1\"\]/g" doc/install.adoc
#sed -i.$ext "s/\[yada \".*\"\]/\[yada \"$1\"\]/g" README.md
#sed -i.$ext "s/\[yada\/lean \".*\"\]/\[yada\/lean \"$1\"\]/g" README.md
find . -name "*.$ext" -exec rm '{}' \;
