[[getting-started]]
== Getting Started

In this quick tutorial we're going to run a real Clojure project, diving into the code to show how [yada]#yada# is used.

Our project is called 'Edge', a sample project from JUXT to show some of our libraries in action. It link:https://github.com/juxt/edge[lives on GitHub].

We'll clone it first, then build it, then run it, then browse the examples and even make modifications.

So let's get going!

=== Clone

First let's clone the project and change into its working directory.

....
git clone https://github.com/juxt/edge
cd edge/
....

=== Create our own app

....
./bin/app yada.manual/app
cd yada.manual.app
....

=== Build & Run

Next we build and run it, in _development_ mode.

....
../bin/rebel -A:dev 
....

This can take up to a couple of minutes to build and run from scratch so don't worry if you have to wait a bit before you see anything.

....
[Edge] Starting development environment, please wait…
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: fipp.visit, being replaced by: #'fipp.visit/boolean?
[Rebel readline] Type :repl/help for online help info
user=> 
....

=== Start the Server
At the 'user=>' prompt enter '(dev)', then '(go)' to start a server listening by default on port 3000.

....
user=> (dev)
[Edge] Loading Clojure code, please wait...
[Edge] Enter (go) to start the dev system
#object[clojure.lang.Namespace 0x7b598d05 "dev"]
dev=> (go)
[Edge] Website listening on: http://localhost:3000
[Edge] Now make code changes, then enter (reset) here
:initiated
....

=== Browse

Fire up a browser and browse to http://localhost:3000/. You should see a simple `Hello, app!` message.

=== Working with the REPL

We're going to start changing some of Edge's source code soon, and when we do that we'll type `(reset)` on our REPL. So let's try that now.

....
dev=> (reset)
:reloading (edge.bidi.ig yada.manual.app.foo edge.system edge.system.meta edge.yada.ig dev-extras dev user)
:resumed
dev=> 
....

=== Test the service

Let's send an HTTP request to the system to check it is working. We can use a browser to visit http://localhost:3000/ or use `curl` if you have it installed on your system:

....
curl http://localhost:3000/
....

The result should be the same:

....
Hello, app!
....

=== Locate the source code

Fire up an editor and load up the file `src/yada/manual/app/foo.clj`.

Locate the function called `string-resource`.
This returns a simple yada resource which serves a string. 

[source,clojure]
----
(defn string-resource
  [x]
  (yada/as-resource x))
----

It receives the string to serve from config.
Open the file `src/config.edn`, and find the key `:yada.manual.app.foo/string`.
Change `"Hello, app!"` to a message of your choice.
For example, change it to `"Hello Wonderful World!"`.

=== Reset the system

Now we've made a change to Edge's source code, we must tell the system to reset. The system will then detect all the code changes and necessary dependencies to reload.

....
dev=> (reset)
:reloading ()
:resumed
dev=> 
....

Let's test the service again:

....
$ curl http://localhost:3000/
....

You should now see that the change has been made:

....
Hello Wonderful World!
....

Congratulations. You're all up and running with a project built with [yada]#yada#. This will make a great lab to try out your own [yada]#yada# experiments and see what is possible.
