[[getting-started]]
= Getting Started

In this quick tutorial we're going to run a real Clojure project, diving into the code to show how [yada]#yada# is used.

Our project is called 'edge', a sample project from JUXT to show some of our libraries in action. It link:https://github.com/juxt/edge[lives on GitHub].

We'll clone it first, then build it, then run it, then browse the examples and even make modifications.

So let's get going!

== Clone

First let's clone the project and change into its working directory.

[source]
----
git clone https://github.com/juxt/edge
cd edge
----

== Build & Run

Next we build and run it, in _development_ mode.

[source]
----
boot dev
----

This can take up to a couple of minutes to build and run from scratch so don't worry if you have to wait a bit before you see anything.

[source]
----
Starting reload server on ws://localhost:43201
Writing boot_reload.cljs...
Writing boot_cljs_repl.cljs...
09:13:50.368 [clojure-agent-send-off-pool-0] INFO  edge.server - Started web-server on port 3000

Starting file watcher (CTRL-C to quit)...

Compiling {sass}... 3 changed files.
----

== Browse

Fire up a browser and browse to http://localhost:3000/hello. You should see a simple `Hello World` message.

== Connect a REPL

Let's connect a REPL.

Start a new terminal and change into the project's working directory again.

[source]
----
cd edge
----

If the project is still building, wait until you see the following line before trying to connect.

----
nREPL server started on port 5600 on host 127.0.0.1 - nrepl://127.0.0.1:5600
----

Connect a client REPL to this JVM like this:

[source]
----
boot repl
----

This should result in something similar to this:

[source]
----
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_92-b14
        Exit: Control+D or (exit) or (quit)
    Commands: (user/help)
        Docs: (doc function-name-here)
              (find-doc "part-of-name-here")
Find by Name: (find-name "part-of-name-here")
      Source: (source function-name-here)
     Javadoc: (javadoc java-object-or-class-here)
    Examples from clojuredocs.org: [clojuredocs or cdoc]
              (user/clojuredocs name-here)
              (user/clojuredocs "ns-here" "name-here")
user=>
----

We're going to start changing some of edge's source code soon, and when we do that we'll type `(reset)` on our REPL. So let's try that now.

[source]
----
user=> (reset)
:reloading (edge.web edge.api edge.server edge.system user)
:resumed
user=>
----

== View the source

Fire up an editor and load up the file `src/edge/web.clj`.

Locate the function called `content-routes` and search for the `"Hello World!"` string.

[source,clojure]
----
(defn content-routes [_]
  ["/"
   [ <1>
    ["index.html"
     (->
      (templated-page-resource "index.html" (fn [ctx] {:foo "bar" :ctx ctx}))
      (assoc :id ::index))]

    ["" (yada/redirect ::index)]

    ;; Add some pairs (as vectors) here. First item is the path, second is the handler.
    ;; Here's an example
    ["hello" (yada/handler "Hello World!\n")] <2>


<<<<<<< Updated upstream
[source,clojure]
----
["hello" (yada/handler "Hello World!\n")]
----

If you have curl on your machine, use it to send it a web request. Alternatively, use a web browser.

[source]
----
curl -i http://localhost:3000/test
----

You should see something similar to the following:

[source]
----
HTTP/1.1 200 OK
Content-Length: 15
Content-Type: text/plain;charset=utf-8
Last-Modified: Wed, 15 Jun 2016 10:17:03 GMT
Vary: accept-charset
ETag: -1277479543
Server: Aleph/0.4.1
Connection: Keep-Alive
Date: Wed, 15 Jun 2016 10:17:06 GMT

Hello World!
----

Now make a change to this line.

[source,clojure]
----
["hello" (yada/handler "Hello Wonderful World!\n")]
----

Go to your REPL and reset your system to pick up the changes:

[source]
----
user=> (reset)
:reloading (edge.web edge.server edge.system user)
:resumed
----

Try the curl command (or web browser) again and verify the updated result.

If it works, you're now ready to proceed with link:{next}[next chapter], where we will discuss this example in more depth.
=======
    [""
     (-> (yada/as-resource (io/file "target"))
         (assoc :id ::static))]

    ]])
----

<1> The start of a series of vector pairs. These associate URI paths with handlers.
<2> Change the string here from `"Hello World"` to `"Hello Wonderful World"`.

Now go back to your REPL and enter `(reset)`.

Finally, refresh your browser — http://localhost:3000 — and check that the message has changed.

== Introducing Resources

Edge uses a link:https://github.com/juxt/bidi[bidi] route structure to define URI paths.

There are a series of vectors, each with 2 elements. The first element is a pattern which, if matched against the URI's path, causes the handler (the second element) to be selected.

[source,clojure]
----
["hello" (yada/handler "Hello World!\n")]
----

In this line, the first element is "hello". Higher up the tree structure you'll see a "/". This means that `/hello` will match to `(yada/handler "Hello World!\n")`.

Let's focus on this handler. We could put a standard Ring function `(fn [req] {...})` here but instead we choose to create one with `yada/handler`, which is a function that turns a *resource* into a Ring handler.

A *resource* is a Clojure map (or more accurately, a Clojure record) that completely describes the methods, properties, representations, security and other miscellaneous properties of a web resource. The reason we can use a string (`Hello World`) here is because [yada]#yada# contains logic to coerce a string into a resource.

== URIs and Routing

A resource doesn't itself with a resource's identification (its URI). In Edge, that's why we need to combine [yada]#yada# with bidi.

Think of the path as (part of) the *I* in *URI*, and the resource as the *R*. The route structure is where URI paths are associated with the resources they identify. This separation of concerns is very important to grasp. From now on we'll seldom mention URIs, since [yada]#yada# is about _resources_, not routing.

== Examining the response

Let's examine the response to our `/hello` request in more detail, via `curl`. The `-i` option shows us the HTTP headers as well as the body.

[source,curl]
----
curl -i http://localhost:3000/hello
----

should result in a response similar to the following (note that headers may appear in a different order).

[source,http]
----
HTTP/1.1 200 OK
Server: Aleph/0.4.1
Connection: Keep-Alive
Date: Fri, 17 Jun 2016 16:44:23 GMT
Last-Modified: Fri, 17 Jun 2016 16:43:02 GMT
ETag: -1727906851
Content-Type: text/plain;charset=utf-8
Vary: accept-charset
Content-Length: 23
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
----

The first three response headers are added by our webserver, Aleph.

[source,http]
----
Server: Aleph/0.4.0
Connection: Keep-Alive
Date: Fri, 17 Jun 2016 16:44:23 GMT
----

Next we have another date and a string known as the __entity tag__.

[source,http]
----
Last-Modified: Sun, 09 Aug 2015 07:25:10 GMT
ETag: 1462348343
----

The *Last-Modified* header shows when the string `Hello World!` was
created. As Java strings are immutable, yada is able to deduce that the
string's creation date is also the last time it could have been
modified.

The entity tag is computed from the value of the `Hello World!` itself. The same goes for the entity tag. Both are used to support HTTP conditional requests and conflict detection.
>>>>>>> Stashed changes
