[[resources]]
= Resources

In [yada]#yada#'s terminology, a resource is the same as it is in HTTP:

[quote,'RFC 7231 Section 2']
--
The target of an HTTP request is called a "resource".  HTTP does not limit the nature of a resource; it merely defines an interface that might be used to interact with resources.  Each resource is  identified by a Uniform Resource Identifier (URI),
--

We can describe a resource directly using a plain old Clojure map, known as a *resource model*.

Here is an example:

[source,clojure]
----
(require '[yada.yada :refer [resource]])

(def my-resource
  (resource
    {:id :example
     :description "The description to this example resource"
     :summary "An example resource"
     :access-control …
     :properties …
     :parameters {:query … :path … :header …}
     :produces …
     :consumes …
     :consumer …
     :methods {:get … :put … :post … :delete … :patch …}
     :responses …
     :path-info? false
     :sub-resource …
     :logger …
     :interceptor-chain …
     :error-interceptor-chain …
     :custom/other …}))
----

Resource models are constrained by a schema, ensuring they are valid. The purpose of the `yada.yada/resource` function is to check the resource model is valid. The schema will attempt to coerce invalid resource models into their valid equivalents wherever possible. An error will be thrown only after these coercions have been attempted.

(The result of a call to `yada.yada/resource` is actually an instance of the Clojure record `yada.resource/Resource` but you can treat it just like a map)

== Creating a Ring handler

Now we have a valid resource, we can now use it for various purposes. The most obvious of these is to handle requests. We can create a Ring-compatible request handler from a resource with the `yada.yada/handler` function:

[source,clojure]
----
(require '[yada.yada :refer [handler]])

(def my-ring-handler
  (handler my-resource))
----

We can now use this handler in a route.

For example, with Compojure:

[source,clojure]
----
(GET "/my-resource" [] my-ring-handler)
----

Or with link:https://github.com/juxt/bidi[bidi]:

[source,clojure]
----
["/my-resource" my-ring-handler]
----

Note, since [yada]#yada# is aware of bidi's `bidi.ring.Ring` protocol, resources can be used in bidi route structures directly:

[source,clojure]
----
["/my-resource" my-resource]
----

== Resource identity

The optional `:id` entry of the resource model gives the resource a unique identity. You can use whatever you like for the value, but it should be unique. A namespaced keyword is typical:

[source,clojure]
----
{:id :resources/user-profile}
----

The main benefit of giving your resources an identity is when you need to create a hyperlink URL to it.



[[data-abbreviations]]
== Data abbreviations

Parts of the canonical resource model structure can be quite verbose. To
make the job of authoring resource models easier a variety of literal
short-hand forms are available. Short-forms are automatically coerced to
their canonical equivalents, prior to building the request handler.

For example:

[source,clojure]
----
{:produces "text/html"}
----

is automatically coerced to this _canonical_ form:

[source,clojure]
----
{:produces [{:media-type "text/html"}]}
----

[[common-examples]]
== Common examples

There are numerous other short-hands. If in doubt, learn the canonical
form and use that until you discover the short-hand for it. You can
experiment with the `yada.resource` function ahead of time in the REPL.
If you do something that isn't possible, the schema validation errors
should help you figure out why.

[insert table of common coercions here]

[[resource-types]]
== Resource types

A *resource type* is a Clojure types or record that can be automatically
coerced into a **resource model**. These types satisfy the
`yada.protocols.ResourceCoercion` protocol, and any existing type or
record may be extended to do so, using Clojure's `extend-protocol`
macro.

[source,clojure]
----
(extend-type datomic.api.Database
  yada.protocols/ResourceCoercion
  (as-resource [_]
    (resource
      {:properties
        {:last-modified …}
       :methods
        {:get …}}})))
----

The `as-resource` function must return a resource (by calling
`yada.resource`, not just a map).

[[summary]]
== Summary

The resource model is yada's central concept. The following chapters
describe the various aspects of the resource-model in more detail.
